export const SAVE_USER_START = "SAVE_USER_START";
export const SAVE_USER_ERROR = "SAVE_USER_ERROR";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";

export const FETCH_DRIVER_START = "FETCH_DRIVER_START";
export const FETCH_DRIVER_ERROR = "FETCH_DRIVER_ERROR";
export const FETCH_DRIVER_SUCCESS = "FETCH_DRIVER_SUCCESS";

export const ADD_DRIVER_START = "ADD_DRIVER_START";
export const ADD_DRIVER_ERROR = "ADD_DRIVER_ERROR";
export const ADD_DRIVER_SUCCESS = "ADD_DRIVER_SUCCESS";

export const UPDATE_DRIVER_START = "UPDATE_DRIVER_START";
export const UPDATE_DRIVER_ERROR = "UPDATE_DRIVER_ERROR";
export const UPDATE_DRIVER_SUCCESS = "UPDATE_DRIVER_SUCCESS";

